version: '3.8'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    volumes:
      - ./data:/app/data
    depends_on:
      - ollama
    networks:
      - mcp-network
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama-data:/root/.ollama
    command: bash -c "ollama serve & sleep 5 && ollama pull gemma3n:4b && wait"
    networks:
      - mcp-network
volumes:
  ollama-data:
networks:
  mcp-network:
    driver: bridge